baseURL = "dasaibot.com"
languageCode = "en-us"
title = "Das AI Bot"
theme = "kube"
description = ""
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "nirmoy.aiemd@gmail.com"

[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
